// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ubitx_20_ux

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
void ui_event_HomePanel(lv_event_t * e);
lv_obj_t * ui_HomePanel;
lv_obj_t * ui_topMenuPanel;
void ui_event_txStopButton(lv_event_t * e);
lv_obj_t * ui_txStopButton;
lv_obj_t * ui_txStopLabel;
void ui_event_switchVFO(lv_event_t * e);
lv_obj_t * ui_switchVFO;
lv_obj_t * ui_currentVFO;
void ui_event_bandDownButton(lv_event_t * e);
lv_obj_t * ui_bandDownButton;
void ui_event_bandDownLabel(lv_event_t * e);
lv_obj_t * ui_bandDownLabel;
void ui_event_bandUpButton(lv_event_t * e);
lv_obj_t * ui_bandUpButton;
void ui_event_bandUpLabel(lv_event_t * e);
lv_obj_t * ui_bandUpLabel;
void ui_event_modeSelectButton(lv_event_t * e);
lv_obj_t * ui_modeSelectButton;
lv_obj_t * ui_modeSelectLabel;
void ui_event_lockDisplayButton(lv_event_t * e);
lv_obj_t * ui_lockDisplayButton;
lv_obj_t * ui_locKDisplayLabel;
void ui_event_spkToggleButton(lv_event_t * e);
lv_obj_t * ui_spkToggleButton;
lv_obj_t * ui_spkToggleLabel;
lv_obj_t * ui_VFOPanel;
lv_obj_t * ui_VFOUpperPanel;
lv_obj_t * ui_RXTXPanel;
void ui_event_RXButton(lv_event_t * e);
lv_obj_t * ui_RXButton;
lv_obj_t * ui_RXButtonLabel;
void ui_event_TXButton(lv_event_t * e);
lv_obj_t * ui_TXButton;
lv_obj_t * ui_TXButtonLabel;
void ui_event_activeVFOPanel(lv_event_t * e);
lv_obj_t * ui_activeVFOPanel;
void ui_event_activeFreq(lv_event_t * e);
lv_obj_t * ui_activeFreq;
lv_obj_t * ui_modeSelectPanel;
void ui_event_LSBModeButton(lv_event_t * e);
lv_obj_t * ui_LSBModeButton;
lv_obj_t * ui_LSBModeLabel;
void ui_event_USBModeButton(lv_event_t * e);
lv_obj_t * ui_USBModeButton;
lv_obj_t * ui_USBModeLabel;
void ui_event_CWLModeButton(lv_event_t * e);
lv_obj_t * ui_CWLModeButton;
lv_obj_t * ui_CWLModeLabel;
void ui_event_CWUModeButton(lv_event_t * e);
lv_obj_t * ui_CWUModeButton;
lv_obj_t * ui_CWUModeLabel;
void ui_event_VFOLowerPanel(lv_event_t * e);
lv_obj_t * ui_VFOLowerPanel;
lv_obj_t * ui_VFOInactiveFreqPanel;
lv_obj_t * ui_inactiveFreq;
lv_obj_t * ui_inactiveMode;
lv_obj_t * ui_firmwarePanel;
lv_obj_t * ui_firmwareOS;
lv_obj_t * ui_firmwareVersion;
void ui_event_SMeterPanel(lv_event_t * e);
lv_obj_t * ui_SMeterPanel;
lv_obj_t * ui_Panel7;
void ui_event_splitButton(lv_event_t * e);
lv_obj_t * ui_splitButton;
lv_obj_t * ui_splitButtonLabel;
void ui_event_ritButton(lv_event_t * e);
lv_obj_t * ui_ritButton;
lv_obj_t * ui_ritButtonLabel;
void ui_event_ifsButton(lv_event_t * e);
lv_obj_t * ui_ifsButton;
lv_obj_t * ui_ifsButtonLabel;
void ui_event_attButton(lv_event_t * e);
lv_obj_t * ui_attButton;
lv_obj_t * ui_attButtonLabel;
lv_obj_t * ui_Panel1;
void ui_event_tuneRateSelection(lv_event_t * e);
lv_obj_t * ui_tuneRateSelection;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Bar2;
void ui_event_bottomPanel(lv_event_t * e);
lv_obj_t * ui_bottomPanel;
void ui_event_cwSettingsPanel(lv_event_t * e);
lv_obj_t * ui_cwSettingsPanel;
void ui_event_cwInfoCol1Panel(lv_event_t * e);
lv_obj_t * ui_cwInfoCol1Panel;
void ui_event_cwInfoLabel(lv_event_t * e);
lv_obj_t * ui_cwInfoLabel;
void ui_event_cwKeySpeed(lv_event_t * e);
lv_obj_t * ui_cwKeySpeed;
void ui_event_cwSideTone(lv_event_t * e);
lv_obj_t * ui_cwSideTone;
void ui_event_cwInforCol2Panel(lv_event_t * e);
lv_obj_t * ui_cwInforCol2Panel;
void ui_event_cwKeyTypeLabel(lv_event_t * e);
lv_obj_t * ui_cwKeyTypeLabel;
void ui_event_cwKeySpeedUnits(lv_event_t * e);
lv_obj_t * ui_cwKeySpeedUnits;
void ui_event_cwSidetoneUnits(lv_event_t * e);
lv_obj_t * ui_cwSidetoneUnits;
lv_obj_t * ui_ATT_IFS_Panel;
lv_obj_t * ui_ATTPanel;
void ui_event_ATTgraph(lv_event_t * e);
lv_obj_t * ui_ATTgraph;
void ui_event_ATTGraphLabels(lv_event_t * e);
lv_obj_t * ui_ATTGraphLabels;
void ui_event_ATTGraphLabel(lv_event_t * e);
lv_obj_t * ui_ATTGraphLabel;
void ui_event_ATTValueLabel(lv_event_t * e);
lv_obj_t * ui_ATTValueLabel;
lv_obj_t * ui_IFSPanel;
void ui_event_IFSgraph(lv_event_t * e);
lv_obj_t * ui_IFSgraph;
void ui_event_IFSGraphLabels(lv_event_t * e);
lv_obj_t * ui_IFSGraphLabels;
void ui_event_IFSGraphLabel(lv_event_t * e);
lv_obj_t * ui_IFSGraphLabel;
void ui_event_IFSValueLabel(lv_event_t * e);
lv_obj_t * ui_IFSValueLabel;


// SCREEN: ui_CWSettings
void ui_CWSettings_screen_init(void);
lv_obj_t * ui_CWSettings;
lv_obj_t * ui_CWSettingsPanel;
lv_obj_t * ui_CWTitleLabel;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel3;
void ui_event_keyStraightCheckbox(lv_event_t * e);
lv_obj_t * ui_keyStraightCheckbox;
void ui_event_keyIambicACheckbox(lv_event_t * e);
lv_obj_t * ui_keyIambicACheckbox;
void ui_event_keyIambicBCheckbox(lv_event_t * e);
lv_obj_t * ui_keyIambicBCheckbox;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Label10;
void ui_event_wpmArc(lv_event_t * e);
lv_obj_t * ui_wpmArc;
lv_obj_t * ui_cwSpeedWPMLabel;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label12;
void ui_event_cwTXStartDelayArc(lv_event_t * e);
lv_obj_t * ui_cwTXStartDelayArc;
lv_obj_t * ui_cwTXStartDelayLabel;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label14;
void ui_event_sideToneArc(lv_event_t * e);
lv_obj_t * ui_sideToneArc;
lv_obj_t * ui_cwSideToneLabel;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label16;
void ui_event_cwTXEndDelayArc(lv_event_t * e);
lv_obj_t * ui_cwTXEndDelayArc;
lv_obj_t * ui_cwTXEndDelayLabel;
lv_obj_t * ui_Label22;


// SCREEN: ui_VFO
void ui_VFO_screen_init(void);
lv_obj_t * ui_VFO;
lv_obj_t * ui_VFOTuningPanel;
lv_obj_t * ui_VFOTitleLabel;
void ui_event_ImgButton1(lv_event_t * e);
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui_Panel16;
void ui_event_Roller7(lv_event_t * e);
lv_obj_t * ui_Roller7;
void ui_event_Roller6(lv_event_t * e);
lv_obj_t * ui_Roller6;
lv_obj_t * ui_Label30;
void ui_event_Roller5(lv_event_t * e);
lv_obj_t * ui_Roller5;
void ui_event_Roller4(lv_event_t * e);
lv_obj_t * ui_Roller4;
void ui_event_Roller3(lv_event_t * e);
lv_obj_t * ui_Roller3;
lv_obj_t * ui_Label29;
void ui_event_Roller2(lv_event_t * e);
lv_obj_t * ui_Roller2;
void ui_event_Roller1(lv_event_t * e);
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Roller0;
void ui_event_VFOmodeSelectButton(lv_event_t * e);
lv_obj_t * ui_VFOmodeSelectButton;
lv_obj_t * ui_VFOmodeSelectLabel;
lv_obj_t * ui_VFOmodeSelectPanel;
void ui_event_VFOLSBModeButton(lv_event_t * e);
lv_obj_t * ui_VFOLSBModeButton;
lv_obj_t * ui_VFOLSBModeLabel;
void ui_event_VFOUSBModeButton(lv_event_t * e);
lv_obj_t * ui_VFOUSBModeButton;
lv_obj_t * ui_VFOUSBModeLabel;
void ui_event_VFOCWLModeButton(lv_event_t * e);
lv_obj_t * ui_VFOCWLModeButton;
lv_obj_t * ui_VFOCWLModeLabel;
void ui_event_VFOCWUModeButton(lv_event_t * e);
lv_obj_t * ui_VFOCWUModeButton;
lv_obj_t * ui_VFOCWUModeLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HomePanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_txStopButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleStopButton(e);
    }
}
void ui_event_switchVFO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleVFOClicked(e);
    }
}
void ui_event_bandDownButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        bandDownClicked(e);
    }
}
void ui_event_bandDownLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        bandDownClicked(e);
    }
}
void ui_event_bandUpButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        bandUpClicked(e);
    }
}
void ui_event_bandUpLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        bandUpClicked(e);
    }
}
void ui_event_modeSelectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_lockDisplayButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleLockButton(e);
    }
}
void ui_event_spkToggleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleSDRButton(e);
    }
}
void ui_event_RXButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TXButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_activeVFOPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        GOTOHOMEtoVFOPanelClicked(e);
    }
}
void ui_event_activeFreq(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHOMEtoVFOPanelClicked(e);
    }
}
void ui_event_LSBModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeLSB(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_USBModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeUSB(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_CWLModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeCWL(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_CWUModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        setModeCWU(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_VFOLowerPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_SMeterPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_splitButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        splitButtonClicked(e);
    }
}
void ui_event_ritButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ritButtonClicked(e);
    }
}
void ui_event_ifsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ifsButtonClicked(e);
    }
}
void ui_event_attButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        attButtonClicked(e);
    }
}
void ui_event_tuneRateSelection(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        tuneRateSelectionClicked(e);
    }
}
void ui_event_bottomPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_cwSettingsPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwInfoCol1Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwInfoLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwKeySpeed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwSideTone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwInforCol2Panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwKeyTypeLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwKeySpeedUnits(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_cwSidetoneUnits(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOHometoCWPanelClicked(e);
    }
}
void ui_event_ATTgraph(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_ATTValueLabel, target, "", "");
    }
}
void ui_event_ATTGraphLabels(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetATTClicked(e);
    }
}
void ui_event_ATTGraphLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetATTClicked(e);
    }
}
void ui_event_ATTValueLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetATTClicked(e);
    }
}
void ui_event_IFSgraph(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_IFSValueLabel, target, "", "");
    }
}
void ui_event_IFSGraphLabels(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetIFSClicked(e);
    }
}
void ui_event_IFSGraphLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetIFSClicked(e);
    }
}
void ui_event_IFSValueLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetIFSClicked(e);
    }
}
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOCWtoHomePanelClicked(e);
    }
}
void ui_event_keyStraightCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_keyIambicACheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_keyIambicBCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        setCWKeytoStraight(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_keyStraightCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_keyIambicACheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_keyStraightCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_keyIambicBCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        setCWKeyToIambicA(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_keyIambicACheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_keyIambicBCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_keyStraightCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_keyIambicACheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        setCWKeyToIambicB(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_state_modify(ui_keyIambicBCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
    }
}
void ui_event_wpmArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cwWPMArcValueChanged(e);
    }
}
void ui_event_cwTXStartDelayArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cwTXStartDelayArcValueChanged(e);
    }
}
void ui_event_sideToneArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cwsideToneArcValueChanged(e);
    }
}
void ui_event_cwTXEndDelayArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        cwTXEndDelayArcValueChanged(e);
    }
}
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        GOTOVFOtoHomePanelClicked(e);
    }
}
void ui_event_Roller7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller7Changed(e);
    }
}
void ui_event_Roller6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller6Changed(e);
    }
}
void ui_event_Roller5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller5Changed(e);
    }
}
void ui_event_Roller4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller4Changed(e);
    }
}
void ui_event_Roller3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller3Changed(e);
    }
}
void ui_event_Roller2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller2Changed(e);
    }
}
void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        vfoRoller1Changed(e);
    }
}
void ui_event_VFOmodeSelectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_VFOmodeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_VFOLSBModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeLSB(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_VFOmodeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_VFOUSBModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeUSB(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_VFOmodeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_VFOCWLModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeCWL(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_VFOmodeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_VFOCWUModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_VFOmodeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        setModeCWU(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_VFOmodeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_CWSettings_screen_init();
    ui_VFO_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
