// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ubitx_20_ux

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_fullScreenPanel(lv_event_t * e);
lv_obj_t * ui_fullScreenPanel;
lv_obj_t * ui_topMenuPanel;
void ui_event_txStopButton(lv_event_t * e);
lv_obj_t * ui_txStopButton;
lv_obj_t * ui_txStopLabel;
void ui_event_switchVFO(lv_event_t * e);
lv_obj_t * ui_switchVFO;
lv_obj_t * ui_currentVFO;
void ui_event_bandDownButton(lv_event_t * e);
lv_obj_t * ui_bandDownButton;
void ui_event_bandDownLabel(lv_event_t * e);
lv_obj_t * ui_bandDownLabel;
void ui_event_bandUpButton(lv_event_t * e);
lv_obj_t * ui_bandUpButton;
void ui_event_bandUpLabel(lv_event_t * e);
lv_obj_t * ui_bandUpLabel;
void ui_event_modeSelectButton(lv_event_t * e);
lv_obj_t * ui_modeSelectButton;
lv_obj_t * ui_modeSelectLabel;
void ui_event_lockDisplayButton(lv_event_t * e);
lv_obj_t * ui_lockDisplayButton;
lv_obj_t * ui_locKDisplayLabel;
void ui_event_spkToggleButton(lv_event_t * e);
lv_obj_t * ui_spkToggleButton;
lv_obj_t * ui_spkToggleLabel;
lv_obj_t * ui_VFOPanel;
lv_obj_t * ui_VFOUpperPanel;
lv_obj_t * ui_RXTXPanel;
void ui_event_RXButton(lv_event_t * e);
lv_obj_t * ui_RXButton;
lv_obj_t * ui_RXButtonLabel;
void ui_event_TXButton(lv_event_t * e);
lv_obj_t * ui_TXButton;
lv_obj_t * ui_TXButtonLabel;
void ui_event_activeVFOPanel(lv_event_t * e);
lv_obj_t * ui_activeVFOPanel;
lv_obj_t * ui_activeFreq;
lv_obj_t * ui_modeSelectPanel;
void ui_event_LSBModeButton(lv_event_t * e);
lv_obj_t * ui_LSBModeButton;
lv_obj_t * ui_LSBModeLabel;
void ui_event_USBModeButton(lv_event_t * e);
lv_obj_t * ui_USBModeButton;
lv_obj_t * ui_USBModeLabel;
void ui_event_CWLModeButton(lv_event_t * e);
lv_obj_t * ui_CWLModeButton;
lv_obj_t * ui_CWLModeLabel;
void ui_event_CWUModeButton(lv_event_t * e);
lv_obj_t * ui_CWUModeButton;
lv_obj_t * ui_CWUModeLabel;
void ui_event_VFOLowerPanel(lv_event_t * e);
lv_obj_t * ui_VFOLowerPanel;
lv_obj_t * ui_VFOInactiveFreqPanel;
lv_obj_t * ui_inactiveFreq;
lv_obj_t * ui_inactiveMode;
lv_obj_t * ui_firmwarePanel;
lv_obj_t * ui_firmwareOS;
lv_obj_t * ui_firmwareVersion;
void ui_event_SMeterPanel(lv_event_t * e);
lv_obj_t * ui_SMeterPanel;
lv_obj_t * ui_Panel7;
void ui_event_splitButton(lv_event_t * e);
lv_obj_t * ui_splitButton;
lv_obj_t * ui_splitButtonLabel;
void ui_event_ritButton(lv_event_t * e);
lv_obj_t * ui_ritButton;
lv_obj_t * ui_ritButtonLabel;
void ui_event_ifsButton(lv_event_t * e);
lv_obj_t * ui_ifsButton;
lv_obj_t * ui_ifsButtonLabel;
void ui_event_attButton(lv_event_t * e);
lv_obj_t * ui_attButton;
lv_obj_t * ui_attButtonLabel;
lv_obj_t * ui_Panel1;
void ui_event_tuneRateSelection(lv_event_t * e);
lv_obj_t * ui_tuneRateSelection;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Bar2;
void ui_event_keySettingsPanel(lv_event_t * e);
lv_obj_t * ui_keySettingsPanel;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_cwSettingsPanel;
lv_obj_t * ui_cwInfoLabel;
lv_obj_t * ui_cwKeyType;
lv_obj_t * ui_cwKeySpeed;
lv_obj_t * ui_cwKeySpeedUnits;
lv_obj_t * ui_cwSidetone;
lv_obj_t * ui_cwSidetoneUnits;
lv_obj_t * ui_settings_panel;
lv_obj_t * ui_Label1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_verticalfilled[1] = {&ui_img_verticalfilled50_png};
const lv_img_dsc_t * ui_imgset_att120x[1] = {&ui_img_att120x53_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_fullScreenPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_txStopButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleStopButton(e);
    }
}
void ui_event_switchVFO(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleVFOClicked(e);
    }
}
void ui_event_bandDownButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        bandDownClicked(e);
    }
}
void ui_event_bandDownLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        bandDownClicked(e);
    }
}
void ui_event_bandUpButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        bandUpClicked(e);
    }
}
void ui_event_bandUpLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        bandUpClicked(e);
    }
}
void ui_event_modeSelectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_lockDisplayButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleLockButton(e);
    }
}
void ui_event_spkToggleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        toggleSDRButton(e);
    }
}
void ui_event_RXButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TXButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_activeVFOPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_LSBModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeLSB(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_USBModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeUSB(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_CWLModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setModeCWL(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_CWUModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        setModeCWU(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_VFOLowerPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_SMeterPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_splitButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        splitButtonClicked(e);
    }
}
void ui_event_ritButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ritButtonClicked(e);
    }
}
void ui_event_ifsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        ifsButtonClicked(e);
    }
}
void ui_event_attButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        attButtonClicked(e);
    }
}
void ui_event_tuneRateSelection(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        tuneRateSelectionClicked(e);
    }
}
void ui_event_keySettingsPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
