// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ubitx_20

#ifndef _UBITX_20_UI_H
#define _UBITX_20_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_fullScreenPanel;
extern lv_obj_t *ui_topMenuPanel;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label1;
void ui_event_switchVFO( lv_event_t * e);
extern lv_obj_t *ui_switchVFO;
extern lv_obj_t *ui_currentVFO;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_VFOPanel;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_activeFreq;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_inactiveFreq;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_SMeterPanel;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Button12;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Button13;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Panel8;
extern lv_obj_t *ui_Panel9;
extern lv_obj_t *ui_Label19;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_keySettingsPanel;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
