// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ubitx_20_ux

#ifndef _UBITX_20_UX_UI_H
#define _UBITX_20_UX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
void ui_event_HomePanel(lv_event_t * e);
extern lv_obj_t * ui_HomePanel;
extern lv_obj_t * ui_topMenuPanel;
void ui_event_txStopButton(lv_event_t * e);
extern lv_obj_t * ui_txStopButton;
extern lv_obj_t * ui_txStopLabel;
void ui_event_switchVFO(lv_event_t * e);
extern lv_obj_t * ui_switchVFO;
extern lv_obj_t * ui_currentVFO;
void ui_event_bandDownButton(lv_event_t * e);
extern lv_obj_t * ui_bandDownButton;
void ui_event_bandDownLabel(lv_event_t * e);
extern lv_obj_t * ui_bandDownLabel;
void ui_event_bandUpButton(lv_event_t * e);
extern lv_obj_t * ui_bandUpButton;
void ui_event_bandUpLabel(lv_event_t * e);
extern lv_obj_t * ui_bandUpLabel;
void ui_event_modeSelectButton(lv_event_t * e);
extern lv_obj_t * ui_modeSelectButton;
extern lv_obj_t * ui_modeSelectLabel;
void ui_event_lockDisplayButton(lv_event_t * e);
extern lv_obj_t * ui_lockDisplayButton;
extern lv_obj_t * ui_locKDisplayLabel;
void ui_event_spkToggleButton(lv_event_t * e);
extern lv_obj_t * ui_spkToggleButton;
extern lv_obj_t * ui_spkToggleLabel;
extern lv_obj_t * ui_VFOPanel;
extern lv_obj_t * ui_VFOUpperPanel;
extern lv_obj_t * ui_RXTXPanel;
void ui_event_RXButton(lv_event_t * e);
extern lv_obj_t * ui_RXButton;
extern lv_obj_t * ui_RXButtonLabel;
void ui_event_TXButton(lv_event_t * e);
extern lv_obj_t * ui_TXButton;
extern lv_obj_t * ui_TXButtonLabel;
void ui_event_activeFreq(lv_event_t * e);
extern lv_obj_t * ui_activeFreq;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_modeSelectPanel;
void ui_event_LSBModeButton(lv_event_t * e);
extern lv_obj_t * ui_LSBModeButton;
extern lv_obj_t * ui_LSBModeLabel;
void ui_event_USBModeButton(lv_event_t * e);
extern lv_obj_t * ui_USBModeButton;
extern lv_obj_t * ui_USBModeLabel;
void ui_event_CWLModeButton(lv_event_t * e);
extern lv_obj_t * ui_CWLModeButton;
extern lv_obj_t * ui_CWLModeLabel;
void ui_event_CWUModeButton(lv_event_t * e);
extern lv_obj_t * ui_CWUModeButton;
extern lv_obj_t * ui_CWUModeLabel;
extern lv_obj_t * ui_MemPanel;
void ui_event_memStoreButton(lv_event_t * e);
extern lv_obj_t * ui_memStoreButton;
extern lv_obj_t * ui_memStoreLabel1;
void ui_event_memRecallButton(lv_event_t * e);
extern lv_obj_t * ui_memRecallButton;
extern lv_obj_t * ui_memRecallButton1;
void ui_event_VFOLowerPanel(lv_event_t * e);
extern lv_obj_t * ui_VFOLowerPanel;
extern lv_obj_t * ui_VFOInactiveFreqPanel;
extern lv_obj_t * ui_inactiveFreq;
extern lv_obj_t * ui_inactiveMode;
extern lv_obj_t * ui_firmwarePanel;
extern lv_obj_t * ui_firmwareOS;
extern lv_obj_t * ui_firmwareVersion;
void ui_event_SMeterPanel(lv_event_t * e);
extern lv_obj_t * ui_SMeterPanel;
extern lv_obj_t * ui_Panel7;
void ui_event_splitButton(lv_event_t * e);
extern lv_obj_t * ui_splitButton;
extern lv_obj_t * ui_splitButtonLabel;
void ui_event_ritButton(lv_event_t * e);
extern lv_obj_t * ui_ritButton;
extern lv_obj_t * ui_ritButtonLabel;
void ui_event_ifsButton(lv_event_t * e);
extern lv_obj_t * ui_ifsButton;
extern lv_obj_t * ui_ifsButtonLabel;
void ui_event_attButton(lv_event_t * e);
extern lv_obj_t * ui_attButton;
extern lv_obj_t * ui_attButtonLabel;
extern lv_obj_t * ui_Panel1;
void ui_event_tuneRateSelection(lv_event_t * e);
extern lv_obj_t * ui_tuneRateSelection;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Bar2;
void ui_event_bottomPanel(lv_event_t * e);
extern lv_obj_t * ui_bottomPanel;
void ui_event_cwSettingsPanel(lv_event_t * e);
extern lv_obj_t * ui_cwSettingsPanel;
void ui_event_cwInfoCol1Panel(lv_event_t * e);
extern lv_obj_t * ui_cwInfoCol1Panel;
void ui_event_cwInfoLabel(lv_event_t * e);
extern lv_obj_t * ui_cwInfoLabel;
void ui_event_cwKeySpeed(lv_event_t * e);
extern lv_obj_t * ui_cwKeySpeed;
void ui_event_cwSideTone(lv_event_t * e);
extern lv_obj_t * ui_cwSideTone;
void ui_event_cwInforCol2Panel(lv_event_t * e);
extern lv_obj_t * ui_cwInforCol2Panel;
void ui_event_cwKeyTypeLabel(lv_event_t * e);
extern lv_obj_t * ui_cwKeyTypeLabel;
void ui_event_cwKeySpeedUnits(lv_event_t * e);
extern lv_obj_t * ui_cwKeySpeedUnits;
void ui_event_cwSidetoneUnits(lv_event_t * e);
extern lv_obj_t * ui_cwSidetoneUnits;
extern lv_obj_t * ui_ATT_IFS_Panel;
extern lv_obj_t * ui_ATTPanel;
void ui_event_ATTgraph(lv_event_t * e);
extern lv_obj_t * ui_ATTgraph;
void ui_event_ATTGraphLabels(lv_event_t * e);
extern lv_obj_t * ui_ATTGraphLabels;
void ui_event_ATTGraphLabel(lv_event_t * e);
extern lv_obj_t * ui_ATTGraphLabel;
void ui_event_ATTValueLabel(lv_event_t * e);
extern lv_obj_t * ui_ATTValueLabel;
extern lv_obj_t * ui_IFSPanel;
void ui_event_IFSgraph(lv_event_t * e);
extern lv_obj_t * ui_IFSgraph;
void ui_event_IFSGraphLabels(lv_event_t * e);
extern lv_obj_t * ui_IFSGraphLabels;
void ui_event_IFSGraphLabel(lv_event_t * e);
extern lv_obj_t * ui_IFSGraphLabel;
void ui_event_IFSValueLabel(lv_event_t * e);
extern lv_obj_t * ui_IFSValueLabel;
// SCREEN: ui_CWSettings
void ui_CWSettings_screen_init(void);
extern lv_obj_t * ui_CWSettings;
extern lv_obj_t * ui_CWSettingsPanel;
extern lv_obj_t * ui_CWTitleLabel;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel3;
void ui_event_keyStraightCheckbox(lv_event_t * e);
extern lv_obj_t * ui_keyStraightCheckbox;
void ui_event_keyIambicACheckbox(lv_event_t * e);
extern lv_obj_t * ui_keyIambicACheckbox;
void ui_event_keyIambicBCheckbox(lv_event_t * e);
extern lv_obj_t * ui_keyIambicBCheckbox;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label10;
void ui_event_wpmArc(lv_event_t * e);
extern lv_obj_t * ui_wpmArc;
extern lv_obj_t * ui_cwSpeedWPMLabel;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label12;
void ui_event_cwTXStartDelayArc(lv_event_t * e);
extern lv_obj_t * ui_cwTXStartDelayArc;
extern lv_obj_t * ui_cwTXStartDelayLabel;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label14;
void ui_event_sideToneArc(lv_event_t * e);
extern lv_obj_t * ui_sideToneArc;
extern lv_obj_t * ui_cwSideToneLabel;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label16;
void ui_event_cwTXEndDelayArc(lv_event_t * e);
extern lv_obj_t * ui_cwTXEndDelayArc;
extern lv_obj_t * ui_cwTXEndDelayLabel;
extern lv_obj_t * ui_Label22;
// SCREEN: ui_VFO
void ui_VFO_screen_init(void);
extern lv_obj_t * ui_VFO;
extern lv_obj_t * ui_VFOTuningPanel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_VFOTitleLabel1;
extern lv_obj_t * ui_Container2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_vfoSpinBox;
void ui_event_vfo0Digit(lv_event_t * e);
extern lv_obj_t * ui_vfo0Digit;
extern lv_obj_t * ui_decimal1;
extern lv_obj_t * ui_decimal2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel5;
void ui_event_VFOmodeSelectButton1(lv_event_t * e);
extern lv_obj_t * ui_VFOmodeSelectButton1;
extern lv_obj_t * ui_VFOmodeSelectLabel;
extern lv_obj_t * ui_vfoModeSelectPanel;
void ui_event_LSBModeButton1(lv_event_t * e);
extern lv_obj_t * ui_LSBModeButton1;
extern lv_obj_t * ui_LSBModeLabel1;
void ui_event_USBModeButton1(lv_event_t * e);
extern lv_obj_t * ui_USBModeButton1;
extern lv_obj_t * ui_USBModeLabel1;
void ui_event_CWLModeButton1(lv_event_t * e);
extern lv_obj_t * ui_CWLModeButton1;
extern lv_obj_t * ui_CWLModeLabel1;
void ui_event_CWUModeButton1(lv_event_t * e);
extern lv_obj_t * ui_CWUModeButton1;
extern lv_obj_t * ui_CWUModeLabel1;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_436403744);    // assets\att-graph.png
LV_IMG_DECLARE(ui_img_redindicator_png);    // assets\redindicator.png
LV_IMG_DECLARE(ui_img_2028451397);    // assets\ifs-graph.png
LV_IMG_DECLARE(ui_img_greenindicator_png);    // assets\greenindicator.png
LV_IMG_DECLARE(ui_img_homebutton_png);    // assets\homebutton.png

LV_FONT_DECLARE(ui_font_RobertoMonoRegular44);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
