// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: testsimple1

#include "ui.h"

int sw =0;
void buttonClicked(lv_event_t * e)
{
	if( sw == 0) {
		lv_label_set_text(ui_Label1,"Push Me");
		sw = 1;
	} else {
		lv_label_set_text(ui_Label1,"Pusher");
		sw = 0;
	}
}