// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ubitx_20_ux

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void toggleStopButton(lv_event_t * e);
void toggleVFOClicked(lv_event_t * e);
void bandDownClicked(lv_event_t * e);
void bandUpClicked(lv_event_t * e);
void toggleLockButton(lv_event_t * e);
void toggleSDRButton(lv_event_t * e);
void GOTOHOMEtoVFOPanelClicked(lv_event_t * e);
void setModeLSB(lv_event_t * e);
void setModeUSB(lv_event_t * e);
void setModeCWL(lv_event_t * e);
void setModeCWU(lv_event_t * e);
void splitButtonClicked(lv_event_t * e);
void ritButtonClicked(lv_event_t * e);
void ifsButtonClicked(lv_event_t * e);
void attButtonClicked(lv_event_t * e);
void tuneRateSelectionClicked(lv_event_t * e);
void GOTOHometoCWPanelClicked(lv_event_t * e);
void resetATTClicked(lv_event_t * e);
void resetIFSClicked(lv_event_t * e);
void GOTOCWtoHomePanelClicked(lv_event_t * e);
void setCWKeytoStraight(lv_event_t * e);
void setCWKeyToIambicA(lv_event_t * e);
void setCWKeyToIambicB(lv_event_t * e);
void cwWPMArcValueChanged(lv_event_t * e);
void cwTXStartDelayArcValueChanged(lv_event_t * e);
void cwsideToneArcValueChanged(lv_event_t * e);
void cwTXEndDelayArcValueChanged(lv_event_t * e);
void GOTOVFOtoHomePanelClicked(lv_event_t * e);
void vfoRoller7Changed(lv_event_t * e);
void vfoRoller6Changed(lv_event_t * e);
void vfoRoller5Changed(lv_event_t * e);
void vfoRoller4Changed(lv_event_t * e);
void vfoRoller3Changed(lv_event_t * e);
void vfoRoller2Changed(lv_event_t * e);
void vfoRoller1Changed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
