// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: ubitx_20_ux

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fullScreenPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_fullScreenPanel, 320);
    lv_obj_set_height(ui_fullScreenPanel, 240);
    lv_obj_set_align(ui_fullScreenPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_fullScreenPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_fullScreenPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_fullScreenPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fullScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fullScreenPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_fullScreenPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_fullScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_fullScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_fullScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_fullScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_fullScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_fullScreenPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_fullScreenPanel, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fullScreenPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_fullScreenPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_fullScreenPanel, LV_BORDER_SIDE_NONE, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_topMenuPanel = lv_obj_create(ui_fullScreenPanel);
    lv_obj_set_width(ui_topMenuPanel, lv_pct(100));
    lv_obj_set_height(ui_topMenuPanel, lv_pct(15));
    lv_obj_set_x(ui_topMenuPanel, -67);
    lv_obj_set_y(ui_topMenuPanel, 4);
    lv_obj_set_flex_flow(ui_topMenuPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topMenuPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_topMenuPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_topMenuPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topMenuPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_topMenuPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_topMenuPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_topMenuPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_topMenuPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_topMenuPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_topMenuPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_topMenuPanel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_topMenuPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_topMenuPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_topMenuPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_topMenuPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_topMenuPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_topMenuPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_txStopButton = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_txStopButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_txStopButton, 1);
    lv_obj_add_flag(ui_txStopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_txStopButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_txStopLabel = lv_label_create(ui_txStopButton);
    lv_obj_set_width(ui_txStopLabel, 32);
    lv_obj_set_height(ui_txStopLabel, lv_pct(100));
    lv_obj_set_align(ui_txStopLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_txStopLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_txStopLabel, "STOP");
    lv_obj_set_style_text_align(ui_txStopLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txStopLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchVFO = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_switchVFO, lv_pct(100));
    lv_obj_set_flex_grow(ui_switchVFO, 1);
    lv_obj_add_flag(ui_switchVFO, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switchVFO, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_currentVFO = lv_label_create(ui_switchVFO);
    lv_obj_set_width(ui_currentVFO, 32);
    lv_obj_set_height(ui_currentVFO, lv_pct(100));
    lv_obj_set_align(ui_currentVFO, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_currentVFO, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_currentVFO, "VFO A");
    lv_obj_set_style_text_align(ui_currentVFO, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_currentVFO, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bandDownButton = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_bandDownButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_bandDownButton, 1);
    lv_obj_add_flag(ui_bandDownButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bandDownButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_bandDownLabel = lv_label_create(ui_bandDownButton);
    lv_obj_set_width(ui_bandDownLabel, 32);
    lv_obj_set_height(ui_bandDownLabel, lv_pct(100));
    lv_obj_set_align(ui_bandDownLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_bandDownLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_bandDownLabel, "BND-");
    lv_obj_set_style_text_align(ui_bandDownLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bandDownLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bandUpButton = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_bandUpButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_bandUpButton, 1);
    lv_obj_add_flag(ui_bandUpButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bandUpButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_bandUpLabel = lv_label_create(ui_bandUpButton);
    lv_obj_set_width(ui_bandUpLabel, 32);
    lv_obj_set_height(ui_bandUpLabel, lv_pct(100));
    lv_obj_set_align(ui_bandUpLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_bandUpLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_bandUpLabel, "BND+");
    lv_obj_set_style_text_align(ui_bandUpLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bandUpLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_modeSelectButton = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_modeSelectButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_modeSelectButton, 1);
    lv_obj_add_flag(ui_modeSelectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_modeSelectButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_modeSelectLabel = lv_label_create(ui_modeSelectButton);
    lv_obj_set_width(ui_modeSelectLabel, 32);
    lv_obj_set_height(ui_modeSelectLabel, lv_pct(100));
    lv_obj_set_align(ui_modeSelectLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_modeSelectLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_modeSelectLabel, "LSB");
    lv_obj_set_style_text_align(ui_modeSelectLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_modeSelectLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lockDisplayButton = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_lockDisplayButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_lockDisplayButton, 1);
    lv_obj_add_flag(ui_lockDisplayButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lockDisplayButton,
                      LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_locKDisplayLabel = lv_label_create(ui_lockDisplayButton);
    lv_obj_set_width(ui_locKDisplayLabel, 32);
    lv_obj_set_height(ui_locKDisplayLabel, lv_pct(100));
    lv_obj_set_align(ui_locKDisplayLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_locKDisplayLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_locKDisplayLabel, "LOCK");
    lv_obj_set_style_text_align(ui_locKDisplayLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_locKDisplayLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_locKDisplayLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_locKDisplayLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_locKDisplayLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_locKDisplayLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_locKDisplayLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_locKDisplayLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spkToggleButton = lv_btn_create(ui_topMenuPanel);
    lv_obj_set_height(ui_spkToggleButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_spkToggleButton, 1);
    lv_obj_add_flag(ui_spkToggleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_spkToggleButton,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_spkToggleLabel = lv_label_create(ui_spkToggleButton);
    lv_obj_set_width(ui_spkToggleLabel, 32);
    lv_obj_set_height(ui_spkToggleLabel, lv_pct(100));
    lv_obj_set_align(ui_spkToggleLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_spkToggleLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_spkToggleLabel, "SPK");
    lv_obj_set_style_text_align(ui_spkToggleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_spkToggleLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VFOPanel = lv_obj_create(ui_fullScreenPanel);
    lv_obj_set_height(ui_VFOPanel, 70);
    lv_obj_set_width(ui_VFOPanel, lv_pct(100));
    lv_obj_set_align(ui_VFOPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VFOPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_VFOPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_VFOPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VFOPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VFOPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VFOUpperPanel = lv_obj_create(ui_VFOPanel);
    lv_obj_set_height(ui_VFOUpperPanel, 50);
    lv_obj_set_width(ui_VFOUpperPanel, lv_pct(100));
    lv_obj_set_align(ui_VFOUpperPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_VFOUpperPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VFOUpperPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VFOUpperPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VFOUpperPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VFOUpperPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VFOUpperPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RXTXPanel = lv_obj_create(ui_VFOUpperPanel);
    lv_obj_set_width(ui_RXTXPanel, lv_pct(20));
    lv_obj_set_height(ui_RXTXPanel, lv_pct(100));
    lv_obj_set_align(ui_RXTXPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RXTXPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_RXTXPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_RXTXPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RXTXPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RXTXPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RXTXPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RXTXPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RXTXPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RXTXPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RXTXPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RXTXPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_RXTXPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RXTXPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RXButton = lv_btn_create(ui_RXTXPanel);
    lv_obj_set_height(ui_RXButton, 20);
    lv_obj_set_width(ui_RXButton, lv_pct(90));
    lv_obj_set_align(ui_RXButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RXButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RXButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RXButton, lv_color_hex(0x04FE7E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RXButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RXButtonLabel = lv_label_create(ui_RXButton);
    lv_obj_set_width(ui_RXButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RXButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RXButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RXButtonLabel, "RX");
    lv_obj_set_style_text_color(ui_RXButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RXButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RXButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TXButton = lv_btn_create(ui_RXTXPanel);
    lv_obj_set_height(ui_TXButton, 20);
    lv_obj_set_width(ui_TXButton, lv_pct(90));
    lv_obj_set_align(ui_TXButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TXButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TXButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TXButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TXButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TXButton, lv_color_hex(0xF40B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TXButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TXButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TXButtonLabel = lv_label_create(ui_TXButton);
    lv_obj_set_width(ui_TXButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TXButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TXButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TXButtonLabel, "TX");
    lv_obj_set_style_text_color(ui_TXButtonLabel, lv_color_hex(0xF40B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TXButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TXButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_activeVFOPanel = lv_obj_create(ui_VFOUpperPanel);
    lv_obj_set_width(ui_activeVFOPanel, lv_pct(80));
    lv_obj_set_height(ui_activeVFOPanel, lv_pct(100));
    lv_obj_set_align(ui_activeVFOPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_activeVFOPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_activeVFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_activeVFOPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_activeVFOPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_activeVFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_activeVFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_activeVFOPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_activeFreq = lv_label_create(ui_activeVFOPanel);
    lv_obj_set_width(ui_activeFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_activeFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_activeFreq, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_activeFreq, "10.103.100");
    lv_obj_set_style_text_color(ui_activeFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_activeFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_activeFreq, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_modeSelectPanel = lv_obj_create(ui_VFOUpperPanel);
    lv_obj_set_width(ui_modeSelectPanel, 175);
    lv_obj_set_height(ui_modeSelectPanel, 30);
    lv_obj_set_x(ui_modeSelectPanel, 44);
    lv_obj_set_y(ui_modeSelectPanel, -9);
    lv_obj_set_align(ui_modeSelectPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_modeSelectPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_modeSelectPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_modeSelectPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_modeSelectPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_modeSelectPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_modeSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_modeSelectPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LSBModeButton = lv_btn_create(ui_modeSelectPanel);
    lv_obj_set_height(ui_LSBModeButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_LSBModeButton, 1);
    lv_obj_add_flag(ui_LSBModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LSBModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_LSBModeLabel = lv_label_create(ui_LSBModeButton);
    lv_obj_set_width(ui_LSBModeLabel, 32);
    lv_obj_set_height(ui_LSBModeLabel, lv_pct(100));
    lv_obj_set_align(ui_LSBModeLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LSBModeLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_LSBModeLabel, "LSB");
    lv_obj_set_style_text_align(ui_LSBModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LSBModeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USBModeButton = lv_btn_create(ui_modeSelectPanel);
    lv_obj_set_height(ui_USBModeButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_USBModeButton, 1);
    lv_obj_add_flag(ui_USBModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USBModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_USBModeLabel = lv_label_create(ui_USBModeButton);
    lv_obj_set_width(ui_USBModeLabel, 32);
    lv_obj_set_height(ui_USBModeLabel, lv_pct(100));
    lv_obj_set_align(ui_USBModeLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_USBModeLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_USBModeLabel, "USB");
    lv_obj_set_style_text_align(ui_USBModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_USBModeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CWLModeButton = lv_btn_create(ui_modeSelectPanel);
    lv_obj_set_height(ui_CWLModeButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_CWLModeButton, 1);
    lv_obj_add_flag(ui_CWLModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CWLModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_CWLModeLabel = lv_label_create(ui_CWLModeButton);
    lv_obj_set_width(ui_CWLModeLabel, 32);
    lv_obj_set_height(ui_CWLModeLabel, lv_pct(100));
    lv_obj_set_align(ui_CWLModeLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_CWLModeLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_CWLModeLabel, "CWL");
    lv_obj_set_style_text_align(ui_CWLModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CWLModeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CWUModeButton = lv_btn_create(ui_modeSelectPanel);
    lv_obj_set_height(ui_CWUModeButton, lv_pct(100));
    lv_obj_set_flex_grow(ui_CWUModeButton, 1);
    lv_obj_add_flag(ui_CWUModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CWUModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_CWUModeLabel = lv_label_create(ui_CWUModeButton);
    lv_obj_set_width(ui_CWUModeLabel, 32);
    lv_obj_set_height(ui_CWUModeLabel, lv_pct(100));
    lv_obj_set_align(ui_CWUModeLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_CWUModeLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_CWUModeLabel, "CWU");
    lv_obj_set_style_text_align(ui_CWUModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CWUModeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VFOLowerPanel = lv_obj_create(ui_VFOPanel);
    lv_obj_set_height(ui_VFOLowerPanel, 20);
    lv_obj_set_width(ui_VFOLowerPanel, lv_pct(100));
    lv_obj_set_align(ui_VFOLowerPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_VFOLowerPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VFOLowerPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VFOLowerPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VFOLowerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VFOLowerPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VFOLowerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VFOLowerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VFOLowerPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VFOLowerPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_VFOLowerPanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VFOLowerPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VFOLowerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VFOLowerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VFOLowerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VFOLowerPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VFOLowerPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VFOLowerPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VFOLowerPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_VFOInactiveFreqPanel = lv_obj_create(ui_VFOLowerPanel);
    lv_obj_set_width(ui_VFOInactiveFreqPanel, lv_pct(45));
    lv_obj_set_height(ui_VFOInactiveFreqPanel, lv_pct(100));
    lv_obj_set_align(ui_VFOInactiveFreqPanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_VFOInactiveFreqPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VFOInactiveFreqPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VFOInactiveFreqPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VFOInactiveFreqPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VFOInactiveFreqPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VFOInactiveFreqPanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inactiveFreq = lv_label_create(ui_VFOInactiveFreqPanel);
    lv_obj_set_width(ui_inactiveFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inactiveFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_inactiveFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_inactiveFreq, "14.032.000");
    lv_obj_set_style_text_color(ui_inactiveFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inactiveFreq, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_inactiveMode = lv_label_create(ui_VFOInactiveFreqPanel);
    lv_obj_set_width(ui_inactiveMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_inactiveMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_inactiveMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_inactiveMode, "CWL");
    lv_obj_set_style_text_color(ui_inactiveMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_inactiveMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_inactiveMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_inactiveMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_inactiveMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_inactiveMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_inactiveMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_inactiveMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwarePanel = lv_obj_create(ui_VFOLowerPanel);
    lv_obj_set_width(ui_firmwarePanel, lv_pct(45));
    lv_obj_set_height(ui_firmwarePanel, lv_pct(100));
    lv_obj_set_align(ui_firmwarePanel, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_firmwarePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_firmwarePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_firmwarePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_firmwarePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_firmwarePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_firmwarePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_firmwarePanel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareOS = lv_label_create(ui_firmwarePanel);
    lv_obj_set_width(ui_firmwareOS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareOS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_firmwareOS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareOS, "CEC");
    lv_obj_set_style_text_color(ui_firmwareOS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firmwareOS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_firmwareOS, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_firmwareOS, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_firmwareOS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_firmwareOS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_firmwareOS, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareVersion = lv_label_create(ui_firmwarePanel);
    lv_obj_set_width(ui_firmwareVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_firmwareVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareVersion, "V2.0");
    lv_obj_set_style_text_color(ui_firmwareVersion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firmwareVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_firmwareVersion, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_firmwareVersion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_firmwareVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_firmwareVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_firmwareVersion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SMeterPanel = lv_obj_create(ui_fullScreenPanel);
    lv_obj_set_height(ui_SMeterPanel, 57);
    lv_obj_set_width(ui_SMeterPanel, lv_pct(100));
    lv_obj_set_align(ui_SMeterPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SMeterPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SMeterPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SMeterPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SMeterPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SMeterPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SMeterPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SMeterPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SMeterPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_SMeterPanel);
    lv_obj_set_height(ui_Panel7, 20);
    lv_obj_set_width(ui_Panel7, lv_pct(100));
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splitButton = lv_btn_create(ui_Panel7);
    lv_obj_set_height(ui_splitButton, 20);
    lv_obj_set_width(ui_splitButton, lv_pct(15));
    lv_obj_set_x(ui_splitButton, 0);
    lv_obj_set_y(ui_splitButton, -1);
    lv_obj_set_align(ui_splitButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splitButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_splitButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_splitButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_splitButton, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splitButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splitButtonLabel = lv_label_create(ui_splitButton);
    lv_obj_set_width(ui_splitButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_splitButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_splitButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_splitButtonLabel, "SPLT");
    lv_obj_set_style_text_color(ui_splitButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_splitButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_splitButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ritButton = lv_btn_create(ui_Panel7);
    lv_obj_set_height(ui_ritButton, 20);
    lv_obj_set_width(ui_ritButton, lv_pct(15));
    lv_obj_set_align(ui_ritButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ritButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ritButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ritButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ritButton, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ritButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ritButtonLabel = lv_label_create(ui_ritButton);
    lv_obj_set_width(ui_ritButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ritButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ritButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ritButtonLabel, "RIT");
    lv_obj_set_style_text_color(ui_ritButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ritButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ritButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ifsButton = lv_btn_create(ui_Panel7);
    lv_obj_set_height(ui_ifsButton, 20);
    lv_obj_set_width(ui_ifsButton, lv_pct(15));
    lv_obj_set_align(ui_ifsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ifsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ifsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ifsButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ifsButton, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ifsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ifsButtonLabel = lv_label_create(ui_ifsButton);
    lv_obj_set_width(ui_ifsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ifsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ifsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ifsButtonLabel, "IF-S");
    lv_obj_set_style_text_color(ui_ifsButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ifsButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ifsButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_attButton = lv_btn_create(ui_Panel7);
    lv_obj_set_height(ui_attButton, 20);
    lv_obj_set_width(ui_attButton, lv_pct(15));
    lv_obj_set_align(ui_attButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_attButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_attButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_attButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_attButton, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_attButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_attButtonLabel = lv_label_create(ui_attButton);
    lv_obj_set_width(ui_attButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_attButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_attButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_attButtonLabel, "ATT");
    lv_obj_set_style_text_color(ui_attButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_attButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_attButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel1, 116);
    lv_obj_set_height(ui_Panel1, 20);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tuneRateSelection = lv_dropdown_create(ui_Panel1);
    lv_dropdown_set_dir(ui_tuneRateSelection, LV_DIR_LEFT);
    lv_dropdown_set_options(ui_tuneRateSelection, "10\n50\n100\n500\n1000");
    lv_obj_set_width(ui_tuneRateSelection, 60);
    lv_obj_set_height(ui_tuneRateSelection, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_tuneRateSelection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tuneRateSelection, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_tuneRateSelection, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tuneRateSelection, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tuneRateSelection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tuneRateSelection, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tuneRateSelection, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tuneRateSelection, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tuneRateSelection, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_tuneRateSelection, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_tuneRateSelection, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_tuneRateSelection), lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_tuneRateSelection), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Hz");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_SMeterPanel);
    lv_obj_set_height(ui_Panel8, 40);
    lv_obj_set_width(ui_Panel8, lv_pct(86));
    lv_obj_set_x(ui_Panel8, 92);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Panel9, lv_pct(15));
    lv_obj_set_height(ui_Panel9, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel9, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel9, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label19, "S");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel9);
    lv_obj_set_height(ui_Label20, 15);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label20, "PO");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFC0909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Label20, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Panel8);
    lv_obj_set_height(ui_Panel10, 30);
    lv_obj_set_width(ui_Panel10, lv_pct(99));
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel10, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_Panel10);
    lv_bar_set_range(ui_Bar2, 0, 9);
    lv_bar_set_value(ui_Bar2, 2, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Bar2, 10);
    lv_obj_set_width(ui_Bar2, lv_pct(100));
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Bar2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xF90606), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_bottomPanel = lv_obj_create(ui_fullScreenPanel);
    lv_obj_set_width(ui_bottomPanel, lv_pct(100));
    lv_obj_set_height(ui_bottomPanel, LV_SIZE_CONTENT);    /// 99
    lv_obj_set_x(ui_bottomPanel, 2);
    lv_obj_set_y(ui_bottomPanel, -18);
    lv_obj_set_align(ui_bottomPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_bottomPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_bottomPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_bottomPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bottomPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_bottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bottomPanel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_side(ui_bottomPanel, LV_BORDER_SIDE_NONE, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_cwSettingsPanel = lv_obj_create(ui_bottomPanel);
    lv_obj_set_width(ui_cwSettingsPanel, 105);
    lv_obj_set_height(ui_cwSettingsPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_flow(ui_cwSettingsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_cwSettingsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cwSettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cwSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cwSettingsPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cwSettingsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cwSettingsPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cwSettingsPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwSettingsPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwSettingsPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_cwSettingsPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwSettingsPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwSettingsPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwSettingsPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwSettingsPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwSettingsPanel, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_cwInfoCol1Panel = lv_obj_create(ui_cwSettingsPanel);
    lv_obj_set_width(ui_cwInfoCol1Panel, 30);
    lv_obj_set_height(ui_cwInfoCol1Panel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_flex_flow(ui_cwInfoCol1Panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_cwInfoCol1Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_cwInfoCol1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cwInfoCol1Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cwInfoCol1Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cwInfoCol1Panel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwInfoCol1Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwInfoCol1Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwInfoLabel = lv_label_create(ui_cwInfoCol1Panel);
    lv_obj_set_width(ui_cwInfoLabel, 30);
    lv_obj_set_height(ui_cwInfoLabel, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_cwInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cwInfoLabel, "CW");
    lv_obj_set_style_text_color(ui_cwInfoLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cwInfoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cwInfoLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cwInfoLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cwInfoLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cwInfoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwInfoLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwKeySpeed = lv_label_create(ui_cwInfoCol1Panel);
    lv_obj_set_width(ui_cwKeySpeed, 30);
    lv_obj_set_height(ui_cwKeySpeed, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_cwKeySpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cwKeySpeed, "20");
    lv_obj_set_style_text_color(ui_cwKeySpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cwKeySpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cwKeySpeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cwKeySpeed, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cwKeySpeed, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwKeySpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwSidetone = lv_label_create(ui_cwInfoCol1Panel);
    lv_obj_set_width(ui_cwSidetone, 30);
    lv_obj_set_height(ui_cwSidetone, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_cwSidetone, 14);
    lv_obj_set_y(ui_cwSidetone, 42);
    lv_obj_set_align(ui_cwSidetone, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_cwSidetone, "700");
    lv_obj_set_style_text_color(ui_cwSidetone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cwSidetone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_cwSidetone, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cwSidetone, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cwSidetone, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwSidetone, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwInforCol2Panel = lv_obj_create(ui_cwSettingsPanel);
    lv_obj_set_width(ui_cwInforCol2Panel, 70);
    lv_obj_set_height(ui_cwInforCol2Panel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_flex_flow(ui_cwInforCol2Panel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_cwInforCol2Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_cwInforCol2Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cwInforCol2Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cwInforCol2Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cwInforCol2Panel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwInforCol2Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwInforCol2Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwKeyType = lv_label_create(ui_cwInforCol2Panel);
    lv_obj_set_width(ui_cwKeyType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cwKeyType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cwKeyType, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cwKeyType, "iambic-a");
    lv_obj_set_style_text_color(ui_cwKeyType, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cwKeyType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cwKeyType, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwKeyType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwKeyType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwKeyType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwKeyType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwKeyType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwKeyType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwKeySpeedUnits = lv_label_create(ui_cwInforCol2Panel);
    lv_obj_set_width(ui_cwKeySpeedUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cwKeySpeedUnits, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_cwKeySpeedUnits, "wpm");
    lv_obj_set_style_text_color(ui_cwKeySpeedUnits, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cwKeySpeedUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cwKeySpeedUnits, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_cwKeySpeedUnits, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwKeySpeedUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cwSidetoneUnits = lv_label_create(ui_cwInforCol2Panel);
    lv_obj_set_width(ui_cwSidetoneUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cwSidetoneUnits, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_cwSidetoneUnits, "Hz");
    lv_obj_set_style_text_color(ui_cwSidetoneUnits, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cwSidetoneUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cwSidetoneUnits, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_cwSidetoneUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_cwSidetoneUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_cwSidetoneUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_cwSidetoneUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_cwSidetoneUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_cwSidetoneUnits, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATT_IFS_Panel = lv_obj_create(ui_bottomPanel);
    lv_obj_set_width(ui_ATT_IFS_Panel, 200);
    lv_obj_set_height(ui_ATT_IFS_Panel, 60);
    lv_obj_set_align(ui_ATT_IFS_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ATT_IFS_Panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ATT_IFS_Panel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_ATT_IFS_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ATT_IFS_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ATT_IFS_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ATT_IFS_Panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ATT_IFS_Panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTPanel = lv_obj_create(ui_ATT_IFS_Panel);
    lv_obj_set_width(ui_ATTPanel, 100);
    lv_obj_set_height(ui_ATTPanel, 60);
    lv_obj_set_align(ui_ATTPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ATTPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ATTPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ATTPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ATTPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ATTPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ATTPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ATTPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ATTPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTgraph = lv_slider_create(ui_ATTPanel);
    lv_slider_set_range(ui_ATTgraph, 0, 255);
    lv_obj_set_width(ui_ATTgraph, 80);
    lv_obj_set_flex_grow(ui_ATTgraph, 1);
    lv_obj_set_x(ui_ATTgraph, 41);
    lv_obj_set_y(ui_ATTgraph, -15);
    lv_obj_set_style_radius(ui_ATTgraph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ATTgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ATTgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ATTgraph, &ui_img_436403744, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ATTgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ATTgraph, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ATTgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_ATTgraph, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ATTgraph, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ATTgraph, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ATTgraph, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ATTgraph, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ATTgraph, &ui_img_indicator_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ATTGraphLabels = lv_obj_create(ui_ATTPanel);
    lv_obj_set_width(ui_ATTGraphLabels, 100);
    lv_obj_set_height(ui_ATTGraphLabels, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ATTGraphLabels, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ATTGraphLabels, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ATTGraphLabels, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ATTGraphLabels, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ATTGraphLabels, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ATTGraphLabels, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ATTGraphLabels, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ATTGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ATTGraphLabels, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTGraphLabel = lv_label_create(ui_ATTGraphLabels);
    lv_obj_set_width(ui_ATTGraphLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTGraphLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ATTGraphLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTGraphLabel, "ATT");
    lv_obj_set_style_text_color(ui_ATTGraphLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTGraphLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ATTGraphLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ATTGraphLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ATTValueLabel = lv_label_create(ui_ATTGraphLabels);
    lv_obj_set_width(ui_ATTValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ATTValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ATTValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ATTValueLabel, "0");
    lv_obj_set_style_text_color(ui_ATTValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ATTValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ATTValueLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ATTValueLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IFSPanel = lv_obj_create(ui_ATT_IFS_Panel);
    lv_obj_set_width(ui_IFSPanel, 100);
    lv_obj_set_height(ui_IFSPanel, 60);
    lv_obj_set_align(ui_IFSPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IFSPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_IFSPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_IFSPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IFSPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IFSPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_IFSPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_IFSPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IFSgraph = lv_slider_create(ui_IFSPanel);
    lv_slider_set_range(ui_IFSgraph, -2000, 2000);
    lv_slider_set_mode(ui_IFSgraph, LV_SLIDER_MODE_SYMMETRICAL);
    lv_obj_set_width(ui_IFSgraph, 80);
    lv_obj_set_flex_grow(ui_IFSgraph, 1);
    lv_obj_set_x(ui_IFSgraph, 41);
    lv_obj_set_y(ui_IFSgraph, -15);
    lv_obj_set_style_radius(ui_IFSgraph, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IFSgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IFSgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_IFSgraph, &ui_img_436403744, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_IFSgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_IFSgraph, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_IFSgraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_IFSgraph, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IFSgraph, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IFSgraph, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_IFSgraph, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IFSgraph, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_IFSgraph, &ui_img_indicator_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_IFSGraphLabels = lv_obj_create(ui_IFSPanel);
    lv_obj_set_width(ui_IFSGraphLabels, 100);
    lv_obj_set_height(ui_IFSGraphLabels, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_IFSGraphLabels, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IFSGraphLabels, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IFSGraphLabels, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_IFSGraphLabels, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_IFSGraphLabels, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IFSGraphLabels, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_IFSGraphLabels, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_IFSGraphLabels, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_IFSGraphLabels, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IFSGraphLabel = lv_label_create(ui_IFSGraphLabels);
    lv_obj_set_width(ui_IFSGraphLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IFSGraphLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IFSGraphLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IFSGraphLabel, "IFS");
    lv_obj_set_style_text_color(ui_IFSGraphLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IFSGraphLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IFSGraphLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_IFSGraphLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IFSGraphLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IFSValueLabel = lv_label_create(ui_IFSGraphLabels);
    lv_obj_set_width(ui_IFSValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IFSValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IFSValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IFSValueLabel, "0");
    lv_obj_set_style_text_color(ui_IFSValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IFSValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IFSValueLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IFSValueLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_settings_panel, 320);
    lv_obj_set_height(ui_settings_panel, 240);
    lv_obj_set_align(ui_settings_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settings_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_settings_panel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Settings");

    lv_obj_add_event_cb(ui_txStopButton, ui_event_txStopButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchVFO, ui_event_switchVFO, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bandDownLabel, ui_event_bandDownLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bandDownButton, ui_event_bandDownButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bandUpLabel, ui_event_bandUpLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bandUpButton, ui_event_bandUpButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_modeSelectButton, ui_event_modeSelectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lockDisplayButton, ui_event_lockDisplayButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_spkToggleButton, ui_event_spkToggleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RXButton, ui_event_RXButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TXButton, ui_event_TXButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_activeVFOPanel, ui_event_activeVFOPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LSBModeButton, ui_event_LSBModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_USBModeButton, ui_event_USBModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CWLModeButton, ui_event_CWLModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CWUModeButton, ui_event_CWUModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VFOLowerPanel, ui_event_VFOLowerPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_splitButton, ui_event_splitButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ritButton, ui_event_ritButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ifsButton, ui_event_ifsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_attButton, ui_event_attButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tuneRateSelection, ui_event_tuneRateSelection, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SMeterPanel, ui_event_SMeterPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_bottomPanel, ui_event_bottomPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_fullScreenPanel, ui_event_fullScreenPanel, LV_EVENT_ALL, NULL);

}
