// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: ubitx_20test

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_add_flag( ui_Screen1, LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLL_ELASTIC );    /// Flags
lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_flex_flow(ui_Screen1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Screen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fullScreenPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_fullScreenPanel, 320);
lv_obj_set_height( ui_fullScreenPanel, 240);
lv_obj_set_align( ui_fullScreenPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_fullScreenPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_fullScreenPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_fullScreenPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_fullScreenPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_fullScreenPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fullScreenPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fullScreenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fullScreenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fullScreenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fullScreenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_fullScreenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_fullScreenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_fullScreenPanel, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_fullScreenPanel, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_fullScreenPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_fullScreenPanel, LV_BORDER_SIDE_NONE, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_topMenuPanel = lv_obj_create(ui_fullScreenPanel);
lv_obj_set_width( ui_topMenuPanel, lv_pct(100));
lv_obj_set_height( ui_topMenuPanel, lv_pct(15));
lv_obj_set_x( ui_topMenuPanel, -67 );
lv_obj_set_y( ui_topMenuPanel, 4 );
lv_obj_set_flex_flow(ui_topMenuPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_topMenuPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_topMenuPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_topMenuPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topMenuPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_topMenuPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_topMenuPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_topMenuPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_topMenuPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_topMenuPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_topMenuPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_topMenuPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_topMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_topMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_topMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_topMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_topMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_topMenuPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_txStopButton = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_txStopButton, lv_pct(100));
lv_obj_set_flex_grow( ui_txStopButton, 1);
lv_obj_add_flag( ui_txStopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_txStopButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txStopLabel = lv_label_create(ui_txStopButton);
lv_obj_set_width( ui_txStopLabel, 32);
lv_obj_set_height( ui_txStopLabel, lv_pct(100));
lv_obj_set_align( ui_txStopLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_txStopLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_txStopLabel,"STOP");
lv_obj_set_style_text_align(ui_txStopLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_txStopLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_switchVFO = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_switchVFO, lv_pct(100));
lv_obj_set_flex_grow( ui_switchVFO, 1);
lv_obj_add_flag( ui_switchVFO, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_switchVFO, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_currentVFO = lv_label_create(ui_switchVFO);
lv_obj_set_width( ui_currentVFO, 32);
lv_obj_set_height( ui_currentVFO, lv_pct(100));
lv_obj_set_align( ui_currentVFO, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_currentVFO,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_currentVFO,"VFO A");
lv_obj_set_style_text_align(ui_currentVFO, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_currentVFO, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bandDownButton = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_bandDownButton, lv_pct(100));
lv_obj_set_flex_grow( ui_bandDownButton, 1);
lv_obj_add_flag( ui_bandDownButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_bandDownButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bandDownLabel = lv_label_create(ui_bandDownButton);
lv_obj_set_width( ui_bandDownLabel, 32);
lv_obj_set_height( ui_bandDownLabel, lv_pct(100));
lv_obj_set_align( ui_bandDownLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_bandDownLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_bandDownLabel,"BND-");
lv_obj_set_style_text_align(ui_bandDownLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bandDownLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bandUpButton = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_bandUpButton, lv_pct(100));
lv_obj_set_flex_grow( ui_bandUpButton, 1);
lv_obj_add_flag( ui_bandUpButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_bandUpButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_bandUpLabel = lv_label_create(ui_bandUpButton);
lv_obj_set_width( ui_bandUpLabel, 32);
lv_obj_set_height( ui_bandUpLabel, lv_pct(100));
lv_obj_set_align( ui_bandUpLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_bandUpLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_bandUpLabel,"BND+");
lv_obj_set_style_text_align(ui_bandUpLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bandUpLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_modeSelectButton = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_modeSelectButton, lv_pct(100));
lv_obj_set_flex_grow( ui_modeSelectButton, 1);
lv_obj_add_flag( ui_modeSelectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_modeSelectButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_modeSelectLabel = lv_label_create(ui_modeSelectButton);
lv_obj_set_width( ui_modeSelectLabel, 32);
lv_obj_set_height( ui_modeSelectLabel, lv_pct(100));
lv_obj_set_align( ui_modeSelectLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_modeSelectLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_modeSelectLabel,"LSB");
lv_obj_set_style_text_align(ui_modeSelectLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_modeSelectLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lockDisplayButton = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_lockDisplayButton, lv_pct(100));
lv_obj_set_flex_grow( ui_lockDisplayButton, 1);
lv_obj_add_flag( ui_lockDisplayButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_lockDisplayButton, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_locKDisplayLabel = lv_label_create(ui_lockDisplayButton);
lv_obj_set_width( ui_locKDisplayLabel, 32);
lv_obj_set_height( ui_locKDisplayLabel, lv_pct(100));
lv_obj_set_align( ui_locKDisplayLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_locKDisplayLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_locKDisplayLabel,"LOCK");
lv_obj_set_style_text_align(ui_locKDisplayLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_locKDisplayLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_locKDisplayLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_locKDisplayLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_locKDisplayLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_locKDisplayLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_locKDisplayLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_locKDisplayLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_spkToggleButton = lv_btn_create(ui_topMenuPanel);
lv_obj_set_height( ui_spkToggleButton, lv_pct(100));
lv_obj_set_flex_grow( ui_spkToggleButton, 1);
lv_obj_add_flag( ui_spkToggleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_spkToggleButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spkToggleLabel = lv_label_create(ui_spkToggleButton);
lv_obj_set_width( ui_spkToggleLabel, 32);
lv_obj_set_height( ui_spkToggleLabel, lv_pct(100));
lv_obj_set_align( ui_spkToggleLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_spkToggleLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_spkToggleLabel,"SPK");
lv_obj_set_style_text_align(ui_spkToggleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_spkToggleLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VFOPanel = lv_obj_create(ui_fullScreenPanel);
lv_obj_set_height( ui_VFOPanel, 70);
lv_obj_set_width( ui_VFOPanel, lv_pct(100));
lv_obj_set_align( ui_VFOPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_VFOPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_VFOPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_VFOPanel, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VFOPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VFOPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_VFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VFOUpperPanel = lv_obj_create(ui_VFOPanel);
lv_obj_set_height( ui_VFOUpperPanel, 50);
lv_obj_set_width( ui_VFOUpperPanel, lv_pct(100));
lv_obj_set_align( ui_VFOUpperPanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_VFOUpperPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_VFOUpperPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_VFOUpperPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VFOUpperPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VFOUpperPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_VFOUpperPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RXTXPanel = lv_obj_create(ui_VFOUpperPanel);
lv_obj_set_width( ui_RXTXPanel, lv_pct(20));
lv_obj_set_height( ui_RXTXPanel, lv_pct(100));
lv_obj_set_align( ui_RXTXPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_RXTXPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_RXTXPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_RXTXPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_RXTXPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RXTXPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RXTXPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RXTXPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_RXTXPanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_RXTXPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_RXTXPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_RXTXPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_RXTXPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_RXTXPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RXButton = lv_btn_create(ui_RXTXPanel);
lv_obj_set_height( ui_RXButton, 20);
lv_obj_set_width( ui_RXButton, lv_pct(90));
lv_obj_set_align( ui_RXButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RXButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_RXButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_RXButton, lv_color_hex(0x04FE7E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RXButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RXButtonLabel = lv_label_create(ui_RXButton);
lv_obj_set_width( ui_RXButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RXButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_RXButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RXButtonLabel,"RX");
lv_obj_set_style_text_color(ui_RXButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RXButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RXButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TXButton = lv_btn_create(ui_RXTXPanel);
lv_obj_set_height( ui_TXButton, 20);
lv_obj_set_width( ui_TXButton, lv_pct(90));
lv_obj_set_align( ui_TXButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TXButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TXButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TXButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TXButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TXButton, lv_color_hex(0xF40B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TXButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TXButton, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TXButtonLabel = lv_label_create(ui_TXButton);
lv_obj_set_width( ui_TXButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TXButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TXButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TXButtonLabel,"TX");
lv_obj_set_style_text_color(ui_TXButtonLabel, lv_color_hex(0xF40B0B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TXButtonLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TXButtonLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_activeVFOPanel = lv_obj_create(ui_VFOUpperPanel);
lv_obj_set_width( ui_activeVFOPanel, lv_pct(80));
lv_obj_set_height( ui_activeVFOPanel, lv_pct(100));
lv_obj_set_align( ui_activeVFOPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_activeVFOPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_activeVFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_activeVFOPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_activeVFOPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_activeVFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_activeVFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_activeVFOPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_activeFreq = lv_label_create(ui_activeVFOPanel);
lv_obj_set_width( ui_activeFreq, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_activeFreq, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_activeFreq, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_activeFreq,"10.103.100");
lv_obj_set_style_text_color(ui_activeFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_activeFreq, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_activeFreq, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_modeSelectPanel = lv_obj_create(ui_VFOUpperPanel);
lv_obj_set_width( ui_modeSelectPanel, 175);
lv_obj_set_height( ui_modeSelectPanel, 30);
lv_obj_set_x( ui_modeSelectPanel, 44 );
lv_obj_set_y( ui_modeSelectPanel, -9 );
lv_obj_set_align( ui_modeSelectPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_modeSelectPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_modeSelectPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_modeSelectPanel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_modeSelectPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_modeSelectPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_modeSelectPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_modeSelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_modeSelectPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LSBModeButton = lv_btn_create(ui_modeSelectPanel);
lv_obj_set_height( ui_LSBModeButton, lv_pct(100));
lv_obj_set_flex_grow( ui_LSBModeButton, 1);
lv_obj_add_flag( ui_LSBModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LSBModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LSBModeLabel = lv_label_create(ui_LSBModeButton);
lv_obj_set_width( ui_LSBModeLabel, 32);
lv_obj_set_height( ui_LSBModeLabel, lv_pct(100));
lv_obj_set_align( ui_LSBModeLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_LSBModeLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_LSBModeLabel,"LSB");
lv_obj_set_style_text_align(ui_LSBModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LSBModeLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USBModeButton = lv_btn_create(ui_modeSelectPanel);
lv_obj_set_height( ui_USBModeButton, lv_pct(100));
lv_obj_set_flex_grow( ui_USBModeButton, 1);
lv_obj_add_flag( ui_USBModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_USBModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_USBModeLabel = lv_label_create(ui_USBModeButton);
lv_obj_set_width( ui_USBModeLabel, 32);
lv_obj_set_height( ui_USBModeLabel, lv_pct(100));
lv_obj_set_align( ui_USBModeLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_USBModeLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_USBModeLabel,"USB");
lv_obj_set_style_text_align(ui_USBModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_USBModeLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CWLModeButton = lv_btn_create(ui_modeSelectPanel);
lv_obj_set_height( ui_CWLModeButton, lv_pct(100));
lv_obj_set_flex_grow( ui_CWLModeButton, 1);
lv_obj_add_flag( ui_CWLModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CWLModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CWLModeLabel = lv_label_create(ui_CWLModeButton);
lv_obj_set_width( ui_CWLModeLabel, 32);
lv_obj_set_height( ui_CWLModeLabel, lv_pct(100));
lv_obj_set_align( ui_CWLModeLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_CWLModeLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_CWLModeLabel,"CWL");
lv_obj_set_style_text_align(ui_CWLModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CWLModeLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CWUModeButton = lv_btn_create(ui_modeSelectPanel);
lv_obj_set_height( ui_CWUModeButton, lv_pct(100));
lv_obj_set_flex_grow( ui_CWUModeButton, 1);
lv_obj_add_flag( ui_CWUModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CWUModeButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_CWUModeLabel = lv_label_create(ui_CWUModeButton);
lv_obj_set_width( ui_CWUModeLabel, 32);
lv_obj_set_height( ui_CWUModeLabel, lv_pct(100));
lv_obj_set_align( ui_CWUModeLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_CWUModeLabel,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_CWUModeLabel,"CWU");
lv_obj_set_style_text_align(ui_CWUModeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CWUModeLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VFOLowerPanel = lv_obj_create(ui_VFOPanel);
lv_obj_set_height( ui_VFOLowerPanel, 20);
lv_obj_set_width( ui_VFOLowerPanel, lv_pct(100));
lv_obj_set_align( ui_VFOLowerPanel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_VFOLowerPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_VFOLowerPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_VFOLowerPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_VFOLowerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VFOLowerPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VFOLowerPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VFOLowerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VFOLowerPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VFOLowerPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_VFOLowerPanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_VFOLowerPanel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VFOLowerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VFOLowerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VFOLowerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_VFOLowerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_VFOLowerPanel, 80, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_VFOLowerPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VFOLowerPanel, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_VFOInactiveFreqPanel = lv_obj_create(ui_VFOLowerPanel);
lv_obj_set_width( ui_VFOInactiveFreqPanel, lv_pct(45));
lv_obj_set_height( ui_VFOInactiveFreqPanel, lv_pct(100));
lv_obj_set_align( ui_VFOInactiveFreqPanel, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_VFOInactiveFreqPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_VFOInactiveFreqPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_VFOInactiveFreqPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_VFOInactiveFreqPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VFOInactiveFreqPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_VFOInactiveFreqPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_VFOInactiveFreqPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inactiveFreq = lv_label_create(ui_VFOInactiveFreqPanel);
lv_obj_set_width( ui_inactiveFreq, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_inactiveFreq, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inactiveFreq, LV_ALIGN_CENTER );
lv_label_set_text(ui_inactiveFreq,"14.032.000");
lv_obj_set_style_text_color(ui_inactiveFreq, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_inactiveFreq, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inactiveMode = lv_label_create(ui_VFOInactiveFreqPanel);
lv_obj_set_width( ui_inactiveMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_inactiveMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inactiveMode, LV_ALIGN_CENTER );
lv_label_set_text(ui_inactiveMode,"CWL");
lv_obj_set_style_text_color(ui_inactiveMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_inactiveMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_inactiveMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_inactiveMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_inactiveMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_inactiveMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_inactiveMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_inactiveMode, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_freqRatePanel = lv_obj_create(ui_VFOLowerPanel);
lv_obj_set_width( ui_freqRatePanel, lv_pct(30));
lv_obj_set_height( ui_freqRatePanel, lv_pct(100));
lv_obj_set_align( ui_freqRatePanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_freqRatePanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_freqRatePanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_freqRatePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_freqRatePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_freqRatePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_freqRatePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_freqRatePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_freqRatePanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_freqRatePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_freqRatePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_freqRatePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_freqRatePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_freqRatePanel, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_freqRatePanel);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label12,"100");
lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_freqRatePanel);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Label13,"Khz");
lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SMeterPanel = lv_obj_create(ui_fullScreenPanel);
lv_obj_set_height( ui_SMeterPanel, 70);
lv_obj_set_width( ui_SMeterPanel, lv_pct(100));
lv_obj_set_align( ui_SMeterPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SMeterPanel,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_SMeterPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SMeterPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SMeterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SMeterPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SMeterPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_SMeterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SMeterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SMeterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SMeterPanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SMeterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SMeterPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SMeterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_SMeterPanel);
lv_obj_set_height( ui_Panel7, 20);
lv_obj_set_width( ui_Panel7, lv_pct(100));
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel7, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button10 = lv_btn_create(ui_Panel7);
lv_obj_set_height( ui_Button10, 20);
lv_obj_set_width( ui_Button10, lv_pct(15));
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Button10);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"SPLT");
lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button11 = lv_btn_create(ui_Panel7);
lv_obj_set_height( ui_Button11, 20);
lv_obj_set_width( ui_Button11, lv_pct(15));
lv_obj_set_align( ui_Button11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label15 = lv_label_create(ui_Button11);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"RIT");
lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button12 = lv_btn_create(ui_Panel7);
lv_obj_set_height( ui_Button12, 20);
lv_obj_set_width( ui_Button12, lv_pct(15));
lv_obj_set_align( ui_Button12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_Button12);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"IF-S");
lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button13 = lv_btn_create(ui_Panel7);
lv_obj_set_height( ui_Button13, 20);
lv_obj_set_width( ui_Button13, lv_pct(15));
lv_obj_set_align( ui_Button13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button13, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x939895), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_Button13);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"ATT");
lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label18 = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"CEC V2.0");
lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label18, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_SMeterPanel);
lv_obj_set_height( ui_Panel8, 40);
lv_obj_set_width( ui_Panel8, lv_pct(86));
lv_obj_set_x( ui_Panel8, 92 );
lv_obj_set_y( ui_Panel8, 0 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel8,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_Panel8);
lv_obj_set_height( ui_Panel9, 34);
lv_obj_set_width( ui_Panel9, lv_pct(15));
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel9,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel9, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label19, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label19,"S");
lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label20 = lv_label_create(ui_Panel9);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label20, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Label20,"PO");
lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFC0909), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel10 = lv_obj_create(ui_Panel8);
lv_obj_set_height( ui_Panel10, 40);
lv_obj_set_width( ui_Panel10, lv_pct(99));
lv_obj_set_align( ui_Panel10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel10,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel10, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel10, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_Panel10);
lv_bar_set_range(ui_Bar2, 0,9);
lv_bar_set_value(ui_Bar2,2,LV_ANIM_OFF);
lv_obj_set_height( ui_Bar2, 10);
lv_obj_set_width( ui_Bar2, lv_pct(100));
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Bar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Bar2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Bar2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Bar2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Bar2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Bar2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xF90606), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_keySettingsPanel = lv_obj_create(ui_fullScreenPanel);
lv_obj_set_width( ui_keySettingsPanel, lv_pct(100));
lv_obj_set_flex_grow( ui_keySettingsPanel, 1);
lv_obj_set_align( ui_keySettingsPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_keySettingsPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_keySettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_keySettingsPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_keySettingsPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_keySettingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_side(ui_keySettingsPanel, LV_BORDER_SIDE_NONE, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_settings_panel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_settings_panel, 320);
lv_obj_set_height( ui_settings_panel, 240);
lv_obj_set_align( ui_settings_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_settings_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_settings_panel);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Settings");

lv_obj_add_event_cb(ui_txStopButton, ui_event_txStopButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_switchVFO, ui_event_switchVFO, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bandDownLabel, ui_event_bandDownLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bandDownButton, ui_event_bandDownButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bandUpLabel, ui_event_bandUpLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bandUpButton, ui_event_bandUpButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_modeSelectButton, ui_event_modeSelectButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_lockDisplayButton, ui_event_lockDisplayButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spkToggleButton, ui_event_spkToggleButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RXButton, ui_event_RXButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TXButton, ui_event_TXButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_activeVFOPanel, ui_event_activeVFOPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LSBModeButton, ui_event_LSBModeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USBModeButton, ui_event_USBModeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CWLModeButton, ui_event_CWLModeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CWUModeButton, ui_event_CWUModeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VFOLowerPanel, ui_event_VFOLowerPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SMeterPanel, ui_event_SMeterPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_keySettingsPanel, ui_event_keySettingsPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_fullScreenPanel, ui_event_fullScreenPanel, LV_EVENT_ALL, NULL);

}
